// actionTypes — shared action type definitions for Logs page + Help page
// Source of truth for action_type categories, tones, and Thai labels

export interface ActionCategory {
  label: string;
  types: string[];
}

export const ACTION_CATEGORIES: ActionCategory[] = [
  { label: "Auth", types: ["login", "logout"] },
  { label: "User mgmt", types: ["user.create", "user.update", "user.delete", "user.toggle_active", "user.reset_password"] },
  { label: "Trigger", types: ["trigger.create", "trigger.update", "trigger.delete", "trigger.toggle"] },
  { label: "Workflow", types: ["workflow.create", "workflow.update", "workflow.delete", "workflow.restore", "workflow.toggle", "workflow.run_completed", "workflow.run_errored", "workflow.run_timeout", "workflow.run_cancelled", "workflow.assign_ticket", "workflow.add_label", "workflow.add_note", "workflow.send_http_blocked", "workflow.resume", "workflow.wait_retry", "workflow.wait_no_reply"] },
  { label: "Knowledge", types: ["kb.create", "kb.update", "kb.delete", "kb.toggle", "kb.import_excel"] },
  { label: "Assignment", types: ["chat_assigned", "chat_reassigned", "assignment.mode_change", "assignment.shop_team_add", "assignment.shop_team_remove", "assignment.platform_team_add", "assignment.platform_team_remove", "agent.pause", "agent.resume", "agent_auto_paused"] },
  { label: "Conversation", types: ["admin.reply", "conversation.handoff", "conversation.resolve", "conversation.open", "conversation.close", "conversation.status_change", "ticket.create", "ticket.update", "ticket.delete"] },
  { label: "Config", types: ["config.update", "config.shop_toggle", "config.test_integration", "admin_config.update", "admin.maintenance.clear_status"] },
  { label: "Bot/Data", types: ["bot.reply", "bot.handoff_to_admin", "bot.process_started", "bot.process_completed", "bot.process_failed", "bot.guard_violation", "bot.idempotency_skip", "bot.buffer_flush", "bot.buffer_recover", "data_writer.message_received", "data_writer.conversation_upserted", "data_writer.duplicate_message", "platform_api.blocked"] },
  { label: "Quick reply", types: ["quick_reply.create", "quick_reply.update", "quick_reply.delete", "quick_reply.use"] },
  { label: "Persona", types: ["shop_persona.create", "shop_persona.update", "shop_persona.delete", "shop_persona.toggle"] },
  { label: "Shop settings", types: ["shop_settings.create", "shop_settings.update", "shop_settings.delete"] },
  { label: "Shadow", types: ["shadow_reply.delete", "shadow_reply.clear_all", "shadow_reply.restore", "shadow_reply.restore_all", "shadow_reply.rate", "shadow_reply.generate", "shadow_reply.generate_conversation"] },
  { label: "Test", types: ["test_chat.rate", "test_assignment.rate_message", "test_assignment.rate_conversation", "test_assignment.replay"] },
  { label: "Chat accept", types: ["chat_accept.start", "chat_accept.stop"] },
  { label: "Conversation meta", types: ["conversation.set_topic", "conversation.set_item_ids", "conversation.pin", "conversation.unpin"] },
  { label: "SLA", types: ["sla.alert", "sla.reassign"] },
];

export const ACTION_TONE: Record<string, "brand" | "coral" | "neutral" | "pale"> = {
  login: "brand",
  logout: "neutral",
  "admin.reply": "brand",
  "conversation.handoff": "coral",
  "conversation.resolve": "neutral",
  "conversation.open": "brand",
  "conversation.close": "neutral",
  "conversation.status_change": "neutral",
  "conversation.set_topic": "pale",
  "conversation.set_item_ids": "pale",
  "conversation.pin": "pale",
  "conversation.unpin": "pale",
  create: "brand",
  update: "brand",
  delete: "coral",
  toggle: "neutral",
  restore: "brand",
  bulk_delete: "coral",
  "bot.reply": "brand",
  "bot.handoff_to_admin": "coral",
  "bot.process_started": "pale",
  "bot.process_completed": "brand",
  "bot.process_failed": "coral",
  "bot.guard_violation": "coral",
  "bot.idempotency_skip": "neutral",
  "bot.buffer_flush": "pale",
  "bot.buffer_recover": "brand",
  "data_writer.message_received": "pale",
  "data_writer.conversation_upserted": "pale",
  "data_writer.duplicate_message": "neutral",
  "platform_api.blocked": "coral",
  "chat_assigned": "brand",
  "chat_reassigned": "brand",
  "assignment.mode_change": "neutral",
  "agent.pause": "coral",
  "agent.resume": "brand",
  agent_auto_paused: "coral",
  "sla.alert": "coral",
  "sla.reassign": "brand",
};

export function actionTypeLabel(t: string): string {
  const map: Record<string, string> = {
    // generic verbs
    create: "สร้าง",
    update: "แก้ไข",
    delete: "ลบ",
    toggle: "เปิด/ปิด",
    restore: "กู้คืน",
    bulk_delete: "ลบหลายรายการ",
    // auth
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    // user
    "user.create": "สร้างผู้ใช้",
    "user.update": "แก้ไขผู้ใช้",
    "user.delete": "ลบผู้ใช้",
    "user.toggle_active": "เปิด/ปิดผู้ใช้",
    "user.reset_password": "รีเซ็ตรหัสผ่าน",
    // trigger
    "trigger.create": "สร้างทริกเกอร์",
    "trigger.update": "แก้ไขทริกเกอร์",
    "trigger.delete": "ลบทริกเกอร์",
    "trigger.toggle": "เปิด/ปิดทริกเกอร์",
    // workflow
    "workflow.create": "สร้างเวิร์กโฟลว์",
    "workflow.update": "แก้ไขเวิร์กโฟลว์",
    "workflow.delete": "ลบเวิร์กโฟลว์",
    "workflow.restore": "กู้คืนเวิร์กโฟลว์",
    "workflow.toggle": "เปิด/ปิดเวิร์กโฟลว์",
    "workflow.run_completed": "รันเวิร์กโฟลว์เสร็จ",
    "workflow.run_errored": "รันเวิร์กโฟลว์ผิดพลาด",
    "workflow.run_timeout": "รันเวิร์กโฟลว์หมดเวลา",
    "workflow.run_cancelled": "ยกเลิกการรันเวิร์กโฟลว์",
    "workflow.assign_ticket": "มอบหมายติ็กเก็ต",
    "workflow.add_label": "เพิ่มป้าย",
    "workflow.add_note": "เพิ่มโน้ต",
    "workflow.send_http_blocked": "บล็อก HTTP",
    "workflow.resume": "ดำเนินต่อเวิร์กโฟลว์",
    "workflow.wait_retry": "รอลองใหม่",
    "workflow.wait_no_reply": "รอไม่มีการตอบ",
    // knowledge
    "kb.create": "สร้างความรู้",
    "kb.update": "แก้ไขความรู้",
    "kb.delete": "ลบความรู้",
    "kb.toggle": "เปิด/ปิดความรู้",
    "kb.import_excel": "นำเข้า Excel",
    // assignment
    chat_assigned: "มอบหมายแชท",
    chat_reassigned: "มอบหมายแชทใหม่",
    "assignment.mode_change": "เปลี่ยนโหมดมอบหมาย",
    "assignment.shop_team_add": "เพิ่มทีมร้าน",
    "assignment.shop_team_remove": "ลบทีมร้าน",
    "assignment.platform_team_add": "เพิ่มทีมแพลตฟอร์ม",
    "assignment.platform_team_remove": "ลบทีมแพลตฟอร์ม",
    "agent.pause": "พักเอเจนต์",
    "agent.resume": "กลับมาทำงานเอเจนต์",
    agent_auto_paused: "พักเอเจนต์อัตโนมัติ",
    // conversation
    "admin.reply": "แอดมินตอบ",
    "conversation.handoff": "ส่งต่อแชท",
    "conversation.resolve": "ปิดแชท",
    "conversation.open": "เปิดแชท",
    "conversation.close": "ปิดแชท",
    "conversation.status_change": "เปลี่ยนสถานะแชท",
    "ticket.create": "สร้างติ็กเก็ต",
    "ticket.update": "แก้ไขติ็กเก็ต",
    "ticket.delete": "ลบติ็กเก็ต",
    // config
    "config.update": "แก้ไขการตั้งค่า",
    "config.shop_toggle": "เปิด/ปิดร้าน",
    "config.test_integration": "ทดสอบการเชื่อมต่อ",
    "admin_config.update": "แก้ไขการตั้งค่าแอดมิน",
    "admin.maintenance.clear_status": "ล้างสถานะบำรุงรักษา",
    // bot/data
    "bot.reply": "บอทตอบ",
    "bot.handoff_to_admin": "บอทส่งต่อแอดมิน",
    "bot.process_started": "บอทเริ่มประมวลผล",
    "bot.process_completed": "บอทประมวลผลเสร็จ",
    "bot.process_failed": "บอทประมวลผลล้มเหลว",
    "bot.guard_violation": "บอทละเมิด guard",
    "bot.idempotency_skip": "บอทข้ามซ้ำ",
    "bot.buffer_flush": "บอท flush buffer",
    "bot.buffer_recover": "บอทกู้คืน buffer",
    "data_writer.message_received": "รับข้อความ",
    "data_writer.conversation_upserted": "บันทึกแชท",
    "data_writer.duplicate_message": "ข้อความซ้ำ",
    "platform_api.blocked": "แพลตฟอร์มบล็อก",
    // quick reply
    "quick_reply.create": "สร้างคำตอบเร็ว",
    "quick_reply.update": "แก้ไขคำตอบเร็ว",
    "quick_reply.delete": "ลบคำตอบเร็ว",
    "quick_reply.use": "ใช้คำตอบเร็ว",
    // persona
    "shop_persona.create": "สร้างเพอร์โซนา",
    "shop_persona.update": "แก้ไขเพอร์โซนา",
    "shop_persona.delete": "ลบเพอร์โซนา",
    "shop_persona.toggle": "เปิด/ปิดเพอร์โซนา",
    // shop settings
    "shop_settings.create": "สร้างตั้งค่าร้าน",
    "shop_settings.update": "แก้ไขตั้งค่าร้าน",
    "shop_settings.delete": "ลบตั้งค่าร้าน",
    // shadow
    "shadow_reply.delete": "ลบเงาคำตอบ",
    "shadow_reply.clear_all": "ล้างเงาคำตอบทั้งหมด",
    "shadow_reply.restore": "กู้คืนเงาคำตอบ",
    "shadow_reply.restore_all": "กู้คืนเงาคำตอบทั้งหมด",
    "shadow_reply.rate": "ให้คะแนนเงาคำตอบ",
    "shadow_reply.generate": "สร้างเงาคำตอบ",
    "shadow_reply.generate_conversation": "สร้างเงาคำตอบแชท",
    // test
    "test_chat.rate": "ทดสอบให้คะแนนแชท",
    "test_assignment.rate_message": "ทดสอบให้คะแนนข้อความ",
    "test_assignment.rate_conversation": "ทดสอบให้คะแนนแชท",
    "test_assignment.replay": "ทดสอบ replay",
    // chat accept
    "chat_accept.start": "เริ่มรับแชท",
    "chat_accept.stop": "หยุดรับแชท",
    // conversation meta
    "conversation.set_topic": "ตั้งหัวข้อแชท",
    "conversation.set_item_ids": "ตั้งสินค้าแชท",
    "conversation.pin": "ปักหมุดแชท",
    "conversation.unpin": "ยกปักหมุดแชท",
    // sla
    "sla.alert": "แจ้งเตือน SLA",
    "sla.reassign": "มอบหมาย SLA ใหม่",
  };
  return map[t] || t;
}
