"""⚡ Device charging-spec database — structured data แทน hardcoded table.

แหล่งข้อมูล: spec sheets ระดับ GSMArena (wired charging watts / connector /
protocol / wireless watts / ปี) — spot-verify รุ่นใหม่ผ่าน web_search

Fields ต่อ entry:
    connector : device-side charging connector
        "usb-c" / "lightning" / "micro-usb" / "proprietary"
    wired_w   : max wired charging input (W) — ใช้เป็น min_watt threshold
    wireless_w: max wireless input (W); 0 = ไม่มี
    protocols : list โปรโตคอลที่เครื่องรับ
        "pd", "pps", "qc", "ufcs", "qi", "qi2", "magsafe",
        "hypercharge", "supervooc", "vooc", "flashcharge", "supercharge", "warp"
    year      : ปีที่ออก (อ้างอิงความใหม่)
    aliases   : ชื่อเรียกอื่นที่ลูกค้าอาจพิมพ์

หมายเหตุ:
- ค่า wired_w = ตัวเลข marketing spec ของเครื่อง (เช่น "90W HyperCharge")
  → accessory ต้องจ่ายได้ ≥ ค่านี้ถึงจะชาร์จเต็มสปีด
- เครื่องโปรโตคอลเจาะจง (hypercharge/supervooc/flashcharge) ใช้กับ adapter
  ทั่วไปได้แต่เร็วตาม protocol ที่ adapter รองรับ — เก็บ protocol ไว้ให้
  LLM/filter ใช้เทียบกับสินค้า
- ไม่มีใน DB → caller fallback ไป web search parse (พฤติกรรมเดิม)
"""

from __future__ import annotations

DEVICE_SPECS: dict[str, dict] = {
    # ══════════════════ Apple — iPhone USB-C era ══════════════════
    "iphone 17 pro max": {"connector": "usb-c", "wired_w": 40, "wireless_w": 25,
                          "protocols": ["pd", "pps", "qi2", "magsafe"], "year": 2025,
                          "aliases": ["iphone 17 promax", "17 pro max", "iphone17 pro max"]},
    "iphone 17 pro":     {"connector": "usb-c", "wired_w": 40, "wireless_w": 25,
                          "protocols": ["pd", "pps", "qi2", "magsafe"], "year": 2025,
                          "aliases": ["iphone17 pro", "17 pro"]},
    "iphone 17":         {"connector": "usb-c", "wired_w": 40, "wireless_w": 25,
                          "protocols": ["pd", "pps", "qi2", "magsafe"], "year": 2025,
                          "aliases": ["iphone17"]},
    "iphone air":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 25,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2025,
                          "aliases": ["iphone 17 air", "apple iphone air"]},
    "iphone 16 pro max": {"connector": "usb-c", "wired_w": 39, "wireless_w": 25,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2024,
                          "aliases": ["iphone 16 promax", "16 pro max"]},
    "iphone 16 pro":     {"connector": "usb-c", "wired_w": 30, "wireless_w": 25,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2024,
                          "aliases": ["16 pro"]},
    "iphone 16 plus":    {"connector": "usb-c", "wired_w": 27, "wireless_w": 25,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2024,
                          "aliases": ["16 plus"]},
    "iphone 16":         {"connector": "usb-c", "wired_w": 27, "wireless_w": 25,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2024,
                          "aliases": ["iphone16"]},
    "iphone 16e":        {"connector": "usb-c", "wired_w": 20, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2025,
                          "aliases": ["16e"]},
    "iphone 15 pro max": {"connector": "usb-c", "wired_w": 27, "wireless_w": 15,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2023,
                          "aliases": ["iphone 15 promax", "15 pro max"]},
    "iphone 15 pro":     {"connector": "usb-c", "wired_w": 27, "wireless_w": 15,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2023,
                          "aliases": ["15 pro"]},
    "iphone 15 plus":    {"connector": "usb-c", "wired_w": 27, "wireless_w": 15,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2023,
                          "aliases": ["15 plus"]},
    "iphone 15":         {"connector": "usb-c", "wired_w": 27, "wireless_w": 15,
                          "protocols": ["pd", "qi2", "magsafe"], "year": 2023,
                          "aliases": ["iphone15"]},
    # ══════════════════ Apple — iPhone Lightning era (PD) ══════════════════
    "iphone 14 pro max": {"connector": "lightning", "wired_w": 27, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2022,
                          "aliases": ["iphone 14 promax", "14 pro max"]},
    "iphone 14 pro":     {"connector": "lightning", "wired_w": 23, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2022, "aliases": ["14 pro"]},
    "iphone 14 plus":    {"connector": "lightning", "wired_w": 20, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2022, "aliases": ["14 plus"]},
    "iphone 14":         {"connector": "lightning", "wired_w": 20, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2022, "aliases": ["iphone14"]},
    "iphone 13 pro max": {"connector": "lightning", "wired_w": 27, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2021,
                          "aliases": ["iphone 13 promax", "13 pro max"]},
    "iphone 13 pro":     {"connector": "lightning", "wired_w": 23, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2021, "aliases": ["13 pro"]},
    "iphone 13":         {"connector": "lightning", "wired_w": 20, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2021, "aliases": ["iphone13"]},
    "iphone 13 mini":    {"connector": "lightning", "wired_w": 20, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2021, "aliases": ["13 mini"]},
    "iphone 12 pro max": {"connector": "lightning", "wired_w": 22, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2020,
                          "aliases": ["12 pro max", "iphone 12 promax"]},
    "iphone 12 pro":     {"connector": "lightning", "wired_w": 20, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2020, "aliases": ["12 pro"]},
    "iphone 12":         {"connector": "lightning", "wired_w": 20, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2020, "aliases": ["iphone12"]},
    "iphone 12 mini":    {"connector": "lightning", "wired_w": 20, "wireless_w": 15,
                          "protocols": ["pd", "magsafe", "qi"], "year": 2020, "aliases": ["12 mini"]},
    "iphone 11 pro max": {"connector": "lightning", "wired_w": 22, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2019, "aliases": ["11 pro max"]},
    "iphone 11 pro":     {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2019, "aliases": ["11 pro"]},
    "iphone 11":         {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2019, "aliases": ["iphone11"]},
    "iphone xs max":     {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2018, "aliases": ["xs max", "iphone xsmax"]},
    "iphone xs":         {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2018, "aliases": []},
    "iphone xr":         {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2018, "aliases": ["iphone x r"]},
    "iphone x":          {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2017, "aliases": ["iphone 10"]},
    "iphone 8 plus":     {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2017, "aliases": ["8 plus", "iphone 8+"]},
    "iphone 8":          {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2017, "aliases": ["iphone8"]},
    "iphone se 3":       {"connector": "lightning", "wired_w": 20, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2022,
                          "aliases": ["iphone se 2022", "se 3", "iphone se 3rd"]},
    "iphone se 2":       {"connector": "lightning", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2020,
                          "aliases": ["iphone se 2020", "se 2", "iphone se 2nd"]},
    # iPhone รุ่นก่อน PD (8 ปี+ ย้อนหลัง) — ไม่รองรับ fast charge
    "iphone 7 plus":     {"connector": "lightning", "wired_w": 10, "wireless_w": 0,
                          "protocols": [], "year": 2016, "aliases": ["7 plus"]},
    "iphone 7":          {"connector": "lightning", "wired_w": 10, "wireless_w": 0,
                          "protocols": [], "year": 2016, "aliases": ["iphone7"]},
    "iphone 6s":         {"connector": "lightning", "wired_w": 10, "wireless_w": 0,
                          "protocols": [], "year": 2015, "aliases": ["6s", "iphone 6 s"]},
    "iphone 6":          {"connector": "lightning", "wired_w": 10, "wireless_w": 0,
                          "protocols": [], "year": 2014, "aliases": ["iphone6"]},
    "iphone 5s":         {"connector": "lightning", "wired_w": 10, "wireless_w": 0,
                          "protocols": [], "year": 2013, "aliases": ["5s", "iphone 5 s"]},
    "iphone 5":          {"connector": "lightning", "wired_w": 10, "wireless_w": 0,
                          "protocols": [], "year": 2012, "aliases": ["iphone5"]},
    # ══════════════════ Apple — iPad ══════════════════
    "ipad pro m5":       {"connector": "usb-c", "wired_w": 40, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2025, "aliases": ["ipad pro 2025"]},
    "ipad pro m4":       {"connector": "usb-c", "wired_w": 35, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024, "aliases": ["ipad pro 2024"]},
    "ipad pro":          {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2022,
                          "aliases": ["ipad pro m2", "ipad pro 2022", "ipad pro 12.9", "ipad pro 11"]},
    "ipad air m3":       {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2025, "aliases": ["ipad air 2025"]},
    "ipad air m2":       {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024, "aliases": ["ipad air 2024"]},
    "ipad air":          {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2022,
                          "aliases": ["ipad air m1", "ipad air 5", "ipad air 4"]},
    "ipad mini 7":       {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024,
                          "aliases": ["ipad mini a17", "ipad mini 2024"]},
    "ipad mini 6":       {"connector": "usb-c", "wired_w": 20, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2021, "aliases": ["ipad mini"]},
    "ipad 11":           {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2025,
                          "aliases": ["ipad gen 11", "ipad a16"]},
    "ipad 10":           {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2022,
                          "aliases": ["ipad gen 10", "ipad 10th"]},
    "ipad 9":            {"connector": "lightning", "wired_w": 20, "wireless_w": 0,
                          "protocols": [], "year": 2021,
                          "aliases": ["ipad gen 9", "ipad 9th"]},
    # ══════════════════ Apple — MacBook (USB-C) ══════════════════
    "macbook pro 16":    {"connector": "usb-c", "wired_w": 140, "wireless_w": 0,
                          "protocols": ["pd", "magsafe"], "year": 2021,
                          "aliases": ["macbook pro 16 m1", "macbook pro 16 m2", "macbook pro 16 m3",
                                      "macbook pro 16 m4", "mbp 16"]},
    "macbook pro 14":    {"connector": "usb-c", "wired_w": 96, "wireless_w": 0,
                          "protocols": ["pd", "magsafe"], "year": 2021,
                          "aliases": ["macbook pro 14 m1", "macbook pro 14 m2", "macbook pro 14 m3",
                                      "macbook pro 14 m4", "mbp 14"]},
    "macbook pro 13":    {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2022,
                          "aliases": ["macbook pro 13 m1", "macbook pro 13 m2", "mbp 13"]},
    "macbook air m4":    {"connector": "usb-c", "wired_w": 70, "wireless_w": 0,
                          "protocols": ["pd", "magsafe"], "year": 2025,
                          "aliases": ["macbook air 2025", "mba m4"]},
    "macbook air m3":    {"connector": "usb-c", "wired_w": 70, "wireless_w": 0,
                          "protocols": ["pd", "magsafe"], "year": 2024,
                          "aliases": ["macbook air 2024", "mba m3", "mac air m3"]},
    "macbook air m2":    {"connector": "usb-c", "wired_w": 70, "wireless_w": 0,
                          "protocols": ["pd", "magsafe"], "year": 2022,
                          "aliases": ["macbook air 2022", "mba m2", "mac air m2"]},
    "macbook air m1":    {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2020,
                          "aliases": ["macbook air 2020", "mba m1", "mac air m1"]},
    "macbook 12":        {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2017, "aliases": ["macbook retina 12"]},
    # ══════════════════ Apple — Watch / AirPods ══════════════════
    "apple watch":       {"connector": "proprietary", "wired_w": 5, "wireless_w": 5,
                          "protocols": [], "year": 2024,
                          "aliases": ["apple watch ultra", "apple watch series", "iwatch"]},
    "airpods pro":       {"connector": "usb-c", "wired_w": 5, "wireless_w": 5,
                          "protocols": ["qi", "magsafe"], "year": 2023,
                          "aliases": ["airpods pro 2", "airpods pro 3", "airpods"]},
    # ══════════════════ Samsung — Galaxy S ══════════════════
    "galaxy s26 ultra":  {"connector": "usb-c", "wired_w": 60, "wireless_w": 25,
                          "protocols": ["pd", "pps", "qi2"], "year": 2026,
                          "aliases": ["s26 ultra", "samsung s26 ultra", "s26u"]},
    "galaxy s26":        {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi2"], "year": 2026, "aliases": ["s26"]},
    "galaxy s25 ultra":  {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025,
                          "aliases": ["s25 ultra", "samsung s25 ultra", "s25u"]},
    "galaxy s25 plus":   {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025, "aliases": ["s25+", "s25 plus"]},
    "galaxy s25":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025, "aliases": ["s25"]},
    "galaxy s25 edge":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025, "aliases": ["s25 edge"]},
    "galaxy s25 fe":     {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025, "aliases": ["s25 fe"]},
    "galaxy s24 ultra":  {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2024,
                          "aliases": ["s24 ultra", "samsung s24 ultra", "s24u"]},
    "galaxy s24 plus":   {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2024, "aliases": ["s24+", "s24 plus"]},
    "galaxy s24":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2024, "aliases": ["s24"]},
    "galaxy s24 fe":     {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2024, "aliases": ["s24 fe"]},
    "galaxy s23 ultra":  {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2023,
                          "aliases": ["s23 ultra", "samsung s23 ultra", "s23u"]},
    "galaxy s23 plus":   {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2023, "aliases": ["s23+", "s23 plus"]},
    "galaxy s23":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2023, "aliases": ["s23"]},
    "galaxy s23 fe":     {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2023, "aliases": ["s23 fe"]},
    "galaxy s22 ultra":  {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2022,
                          "aliases": ["s22 ultra", "samsung s22 ultra", "s22u"]},
    "galaxy s22 plus":   {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2022, "aliases": ["s22+", "s22 plus"]},
    "galaxy s22":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2022, "aliases": ["s22"]},
    "galaxy s21 ultra":  {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2021,
                          "aliases": ["s21 ultra", "samsung s21 ultra", "s21u"]},
    "galaxy s21 plus":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2021, "aliases": ["s21+", "s21 plus"]},
    "galaxy s21":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2021, "aliases": ["s21"]},
    "galaxy s21 fe":     {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2022, "aliases": ["s21 fe"]},
    "galaxy s20 ultra":  {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2020,
                          "aliases": ["s20 ultra", "samsung s20 ultra", "s20u"]},
    "galaxy s20 plus":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2020, "aliases": ["s20+", "s20 plus"]},
    "galaxy s20":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2020, "aliases": ["s20"]},
    "galaxy s20 fe":     {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2020, "aliases": ["s20 fe"]},
    "galaxy note 20 ultra": {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2020,
                          "aliases": ["note 20 ultra", "samsung note 20 ultra"]},
    "galaxy note 10 plus":  {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2019,
                          "aliases": ["note 10+", "note 10 plus", "samsung note 10"]},
    # ══════════════════ Samsung — Galaxy Z / A / Tab ══════════════════
    "galaxy z fold 7":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025, "aliases": ["z fold 7", "fold 7"]},
    "galaxy z fold 6":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2024, "aliases": ["z fold 6", "fold 6"]},
    "galaxy z fold 5":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2023, "aliases": ["z fold 5", "fold 5"]},
    "galaxy z fold 4":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2022, "aliases": ["z fold 4", "fold 4"]},
    "galaxy z fold 3":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 10,
                          "protocols": ["pd", "pps", "qi"], "year": 2021, "aliases": ["z fold 3", "fold 3"]},
    "galaxy z flip 7":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025, "aliases": ["z flip 7", "flip 7"]},
    "galaxy z flip 6":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2024, "aliases": ["z flip 6", "flip 6"]},
    "galaxy z flip 5":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2023, "aliases": ["z flip 5", "flip 5"]},
    "galaxy z flip 4":   {"connector": "usb-c", "wired_w": 25, "wireless_w": 10,
                          "protocols": ["pd", "pps", "qc"], "year": 2022, "aliases": ["z flip 4", "flip 4"]},
    "galaxy z flip 3":   {"connector": "usb-c", "wired_w": 15, "wireless_w": 10,
                          "protocols": ["pd", "qc"], "year": 2021, "aliases": ["z flip 3", "flip 3"]},
    "galaxy a56":        {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2025, "aliases": ["samsung a56", "a56"]},
    "galaxy a55":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2024, "aliases": ["samsung a55", "a55"]},
    "galaxy a54":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2023, "aliases": ["samsung a54", "a54"]},
    "galaxy a36":        {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2025, "aliases": ["samsung a36", "a36"]},
    "galaxy a35":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2024, "aliases": ["samsung a35", "a35"]},
    "galaxy a34":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2023, "aliases": ["samsung a34", "a34"]},
    "galaxy a26":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2025, "aliases": ["samsung a26", "a26"]},
    "galaxy a16":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024, "aliases": ["samsung a16", "a16"]},
    "galaxy a15":        {"connector": "usb-c", "wired_w": 25, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2023, "aliases": ["samsung a15", "a15"]},
    "galaxy tab s10":    {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2024,
                          "aliases": ["tab s10", "samsung tab s10", "galaxy tab s10 ultra"]},
    "galaxy tab s9":     {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2023,
                          "aliases": ["tab s9", "samsung tab s9", "galaxy tab s9 ultra"]},
    "galaxy tab s8":     {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2022,
                          "aliases": ["tab s8", "samsung tab s8", "galaxy tab s8 ultra"]},
    "galaxy watch":      {"connector": "proprietary", "wired_w": 10, "wireless_w": 10,
                          "protocols": ["qi"], "year": 2024,
                          "aliases": ["galaxy watch 7", "galaxy watch ultra", "samsung watch"]},
    # ══════════════════ Xiaomi / Mi / Redmi / Poco ══════════════════
    "xiaomi 17 ultra":   {"connector": "usb-c", "wired_w": 90, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2026,
                          "aliases": ["mi 17 ultra", "mi17 ultra", "xiaomi17 ultra"]},
    "xiaomi 17 pro max": {"connector": "usb-c", "wired_w": 100, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2025,
                          "aliases": ["mi 17 pro max", "17 pro max xiaomi"]},
    "xiaomi 17 pro":     {"connector": "usb-c", "wired_w": 100, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2025,
                          "aliases": ["mi 17 pro"]},
    "xiaomi 17":         {"connector": "usb-c", "wired_w": 100, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2025,
                          "aliases": ["mi 17", "mi17", "xiaomi17"]},
    "xiaomi 15 ultra":   {"connector": "usb-c", "wired_w": 90, "wireless_w": 80,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2025,
                          "aliases": ["mi 15 ultra", "mi15 ultra"]},
    "xiaomi 15 pro":     {"connector": "usb-c", "wired_w": 90, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2024,
                          "aliases": ["mi 15 pro"]},
    "xiaomi 15":         {"connector": "usb-c", "wired_w": 90, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2024,
                          "aliases": ["mi 15", "mi15"]},
    "xiaomi 14 ultra":   {"connector": "usb-c", "wired_w": 90, "wireless_w": 80,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2024,
                          "aliases": ["mi 14 ultra", "mi14 ultra"]},
    "xiaomi 14":         {"connector": "usb-c", "wired_w": 90, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2023,
                          "aliases": ["mi 14", "mi14"]},
    "xiaomi 14t pro":    {"connector": "usb-c", "wired_w": 120, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2024,
                          "aliases": ["mi 14t pro", "14t pro"]},
    "xiaomi 14t":        {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2024,
                          "aliases": ["mi 14t", "14t"]},
    "xiaomi 13 ultra":   {"connector": "usb-c", "wired_w": 90, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2023,
                          "aliases": ["mi 13 ultra", "mi13 ultra"]},
    "xiaomi 13 pro":     {"connector": "usb-c", "wired_w": 120, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "pps", "qc"], "year": 2022,
                          "aliases": ["mi 13 pro"]},
    "xiaomi 13":         {"connector": "usb-c", "wired_w": 67, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2022,
                          "aliases": ["mi 13", "mi13"]},
    "xiaomi 13t pro":    {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2023,
                          "aliases": ["mi 13t pro", "13t pro"]},
    "xiaomi 13t":        {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2023,
                          "aliases": ["mi 13t", "13t"]},
    "xiaomi 12 pro":     {"connector": "usb-c", "wired_w": 120, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2021,
                          "aliases": ["mi 12 pro"]},
    "xiaomi 12":         {"connector": "usb-c", "wired_w": 67, "wireless_w": 50,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2021,
                          "aliases": ["mi 12", "mi12"]},
    "xiaomi 12t":        {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2022,
                          "aliases": ["mi 12t", "12t"]},
    "xiaomi 11 ultra":   {"connector": "usb-c", "wired_w": 67, "wireless_w": 67,
                          "protocols": ["pd", "qc"], "year": 2021, "aliases": ["mi 11 ultra"]},
    "xiaomi 11":         {"connector": "usb-c", "wired_w": 55, "wireless_w": 50,
                          "protocols": ["pd", "qc"], "year": 2020, "aliases": ["mi 11", "mi11"]},
    "xiaomi 11t pro":    {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2021,
                          "aliases": ["mi 11t pro", "11t pro"]},
    "xiaomi pad 7":      {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2024,
                          "aliases": ["mi pad 7", "xiaomi pad 7 pro"]},
    "xiaomi pad 6":      {"connector": "usb-c", "wired_w": 33, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2023, "aliases": ["mi pad 6"]},
    "xiaomi pad 5":      {"connector": "usb-c", "wired_w": 33, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2021, "aliases": ["mi pad 5"]},
    "redmi note 14 pro plus": {"connector": "usb-c", "wired_w": 90, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2024,
                          "aliases": ["redmi note 14 pro+", "note 14 pro plus"]},
    "redmi note 14 pro": {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2024,
                          "aliases": ["note 14 pro", "redmi note 14"]},
    "redmi note 14":     {"connector": "usb-c", "wired_w": 33, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2024, "aliases": ["note 14"]},
    "redmi note 13 pro plus": {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2023,
                          "aliases": ["redmi note 13 pro+", "note 13 pro plus"]},
    "redmi note 13 pro": {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2023, "aliases": ["note 13 pro"]},
    "redmi note 13":     {"connector": "usb-c", "wired_w": 33, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2023, "aliases": ["note 13"]},
    "redmi note 12":     {"connector": "usb-c", "wired_w": 33, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2022, "aliases": ["note 12"]},
    "redmi k80":         {"connector": "usb-c", "wired_w": 90, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2024, "aliases": ["k80"]},
    "redmi k70":         {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2023, "aliases": ["k70"]},
    "redmi k60":         {"connector": "usb-c", "wired_w": 67, "wireless_w": 30,
                          "protocols": ["pd", "qc"], "year": 2022, "aliases": ["k60"]},
    "poco f7":           {"connector": "usb-c", "wired_w": 90, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2025, "aliases": ["poco f7 pro"]},
    "poco f6":           {"connector": "usb-c", "wired_w": 90, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2024, "aliases": ["poco f6 pro"]},
    "poco f5":           {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2023, "aliases": ["poco f5 pro"]},
    "poco x7 pro":       {"connector": "usb-c", "wired_w": 90, "wireless_w": 0,
                          "protocols": ["hypercharge", "pd", "qc"], "year": 2024, "aliases": ["x7 pro"]},
    "poco x6 pro":       {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2024, "aliases": ["x6 pro"]},
    "poco x6":           {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2024, "aliases": ["x6"]},
    # ══════════════════ Huawei / Honor ══════════════════
    "huawei mate 70 pro": {"connector": "usb-c", "wired_w": 100, "wireless_w": 80,
                          "protocols": ["supercharge", "pd", "ufcs"], "year": 2024,
                          "aliases": ["mate 70 pro", "huawei mate 70"]},
    "huawei mate 60 pro": {"connector": "usb-c", "wired_w": 88, "wireless_w": 50,
                          "protocols": ["supercharge", "pd"], "year": 2023,
                          "aliases": ["mate 60 pro", "huawei mate 60"]},
    "huawei mate 50 pro": {"connector": "usb-c", "wired_w": 66, "wireless_w": 50,
                          "protocols": ["supercharge", "pd"], "year": 2022,
                          "aliases": ["mate 50 pro", "huawei mate 50"]},
    "huawei pura 70 ultra": {"connector": "usb-c", "wired_w": 100, "wireless_w": 80,
                          "protocols": ["supercharge", "pd"], "year": 2024,
                          "aliases": ["pura 70 ultra", "huawei pura 70"]},
    "huawei p60 pro":    {"connector": "usb-c", "wired_w": 88, "wireless_w": 50,
                          "protocols": ["supercharge", "pd"], "year": 2023, "aliases": ["p60 pro"]},
    "huawei nova 13":    {"connector": "usb-c", "wired_w": 100, "wireless_w": 0,
                          "protocols": ["supercharge", "pd"], "year": 2024, "aliases": ["nova 13"]},
    "honor magic 7 pro": {"connector": "usb-c", "wired_w": 100, "wireless_w": 80,
                          "protocols": ["supercharge", "pd", "pps"], "year": 2024,
                          "aliases": ["magic 7 pro", "honor magic 7"]},
    "honor magic 6 pro": {"connector": "usb-c", "wired_w": 80, "wireless_w": 66,
                          "protocols": ["supercharge", "pd"], "year": 2024,
                          "aliases": ["magic 6 pro", "honor magic 6"]},
    "honor magic 5 pro": {"connector": "usb-c", "wired_w": 66, "wireless_w": 50,
                          "protocols": ["supercharge", "pd"], "year": 2023,
                          "aliases": ["magic 5 pro", "honor magic 5"]},
    "honor 300":         {"connector": "usb-c", "wired_w": 100, "wireless_w": 0,
                          "protocols": ["supercharge", "pd"], "year": 2024, "aliases": ["honor 300 pro"]},
    "honor 200":         {"connector": "usb-c", "wired_w": 100, "wireless_w": 0,
                          "protocols": ["supercharge", "pd"], "year": 2024, "aliases": ["honor 200 pro"]},
    # ══════════════════ Oppo / OnePlus / Realme ══════════════════
    "oppo find x8 pro":  {"connector": "usb-c", "wired_w": 80, "wireless_w": 50,
                          "protocols": ["supervooc", "pd", "ufcs"], "year": 2024,
                          "aliases": ["find x8 pro", "oppo find x8"]},
    "oppo find x7 ultra": {"connector": "usb-c", "wired_w": 100, "wireless_w": 50,
                          "protocols": ["supervooc", "pd", "ufcs"], "year": 2024,
                          "aliases": ["find x7 ultra", "oppo find x7"]},
    "oppo find x6 pro":  {"connector": "usb-c", "wired_w": 100, "wireless_w": 50,
                          "protocols": ["supervooc", "pd"], "year": 2023,
                          "aliases": ["find x6 pro", "oppo find x6"]},
    "oppo find x5 pro":  {"connector": "usb-c", "wired_w": 80, "wireless_w": 50,
                          "protocols": ["supervooc", "pd"], "year": 2022,
                          "aliases": ["find x5 pro", "oppo find x5"]},
    "oppo reno 13 pro":  {"connector": "usb-c", "wired_w": 80, "wireless_w": 50,
                          "protocols": ["supervooc", "pd"], "year": 2024, "aliases": ["reno 13 pro", "reno 13"]},
    "oppo reno 12 pro":  {"connector": "usb-c", "wired_w": 80, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2024, "aliases": ["reno 12 pro", "reno 12"]},
    "oppo reno 11":      {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2024, "aliases": ["reno 11"]},
    "oneplus 13":        {"connector": "usb-c", "wired_w": 100, "wireless_w": 50,
                          "protocols": ["supervooc", "pd", "ufcs"], "year": 2024,
                          "aliases": ["one plus 13", "op13"]},
    "oneplus 12":        {"connector": "usb-c", "wired_w": 100, "wireless_w": 50,
                          "protocols": ["supervooc", "pd", "ufcs"], "year": 2023,
                          "aliases": ["one plus 12", "op12"]},
    "oneplus 11":        {"connector": "usb-c", "wired_w": 100, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2023,
                          "aliases": ["one plus 11", "op11"]},
    "oneplus 10 pro":    {"connector": "usb-c", "wired_w": 80, "wireless_w": 50,
                          "protocols": ["supervooc", "pd"], "year": 2022,
                          "aliases": ["one plus 10 pro", "op10 pro"]},
    "oneplus nord 4":    {"connector": "usb-c", "wired_w": 100, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2024, "aliases": ["nord 4"]},
    "oneplus nord 3":    {"connector": "usb-c", "wired_w": 80, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2023, "aliases": ["nord 3"]},
    "realme gt 7 pro":   {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["supervooc", "pd", "ufcs"], "year": 2024,
                          "aliases": ["gt 7 pro", "realme gt7 pro"]},
    "realme gt 6":       {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2024, "aliases": ["gt 6", "realme gt6"]},
    "realme gt 5":       {"connector": "usb-c", "wired_w": 240, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2023, "aliases": ["gt 5", "realme gt5"]},
    "realme 13 pro plus": {"connector": "usb-c", "wired_w": 80, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2024,
                          "aliases": ["13 pro+", "realme 13 pro"]},
    "realme 12 pro plus": {"connector": "usb-c", "wired_w": 67, "wireless_w": 0,
                          "protocols": ["supervooc", "pd"], "year": 2024,
                          "aliases": ["12 pro+", "realme 12 pro"]},
    # ══════════════════ Vivo / iQOO ══════════════════
    "vivo x200 pro":     {"connector": "usb-c", "wired_w": 90, "wireless_w": 30,
                          "protocols": ["flashcharge", "pd", "pps"], "year": 2024,
                          "aliases": ["x200 pro", "vivo x200"]},
    "vivo x100 pro":     {"connector": "usb-c", "wired_w": 100, "wireless_w": 50,
                          "protocols": ["flashcharge", "pd"], "year": 2023,
                          "aliases": ["x100 pro", "vivo x100"]},
    "vivo x90 pro":      {"connector": "usb-c", "wired_w": 120, "wireless_w": 50,
                          "protocols": ["flashcharge", "pd"], "year": 2022,
                          "aliases": ["x90 pro", "vivo x90"]},
    "vivo v50":          {"connector": "usb-c", "wired_w": 90, "wireless_w": 0,
                          "protocols": ["flashcharge", "pd"], "year": 2025, "aliases": ["vivo v50 pro"]},
    "vivo v40":          {"connector": "usb-c", "wired_w": 80, "wireless_w": 0,
                          "protocols": ["flashcharge", "pd"], "year": 2024, "aliases": ["vivo v40 pro"]},
    "iqoo 13":           {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["flashcharge", "pd"], "year": 2024, "aliases": ["vivo iqoo 13"]},
    "iqoo 12":           {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["flashcharge", "pd"], "year": 2023, "aliases": ["vivo iqoo 12"]},
    "iqoo 11":           {"connector": "usb-c", "wired_w": 120, "wireless_w": 0,
                          "protocols": ["flashcharge", "pd"], "year": 2022, "aliases": ["vivo iqoo 11"]},
    # ══════════════════ Google Pixel ══════════════════
    "pixel 10 pro xl":   {"connector": "usb-c", "wired_w": 45, "wireless_w": 25,
                          "protocols": ["pd", "pps", "qi2"], "year": 2025,
                          "aliases": ["pixel 10 xl", "google pixel 10 pro xl"]},
    "pixel 10 pro":      {"connector": "usb-c", "wired_w": 30, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi2"], "year": 2025, "aliases": ["google pixel 10 pro"]},
    "pixel 10":          {"connector": "usb-c", "wired_w": 30, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi2"], "year": 2025, "aliases": ["google pixel 10"]},
    "pixel 10 pro fold": {"connector": "usb-c", "wired_w": 30, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi2"], "year": 2025, "aliases": ["pixel fold 2", "pixel 10 fold"]},
    "pixel 9 pro xl":    {"connector": "usb-c", "wired_w": 37, "wireless_w": 23,
                          "protocols": ["pd", "pps", "qi"], "year": 2024,
                          "aliases": ["pixel 9 xl", "google pixel 9 pro xl"]},
    "pixel 9 pro":       {"connector": "usb-c", "wired_w": 27, "wireless_w": 21,
                          "protocols": ["pd", "pps", "qi"], "year": 2024, "aliases": ["google pixel 9 pro"]},
    "pixel 9":           {"connector": "usb-c", "wired_w": 27, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2024, "aliases": ["google pixel 9"]},
    "pixel 9 pro fold":  {"connector": "usb-c", "wired_w": 21, "wireless_w": 7.5,
                          "protocols": ["pd", "pps", "qi"], "year": 2024, "aliases": ["pixel fold 9 pro"]},
    "pixel 9a":          {"connector": "usb-c", "wired_w": 23, "wireless_w": 7.5,
                          "protocols": ["pd", "pps", "qi"], "year": 2025, "aliases": ["google pixel 9a"]},
    "pixel 8 pro":       {"connector": "usb-c", "wired_w": 30, "wireless_w": 23,
                          "protocols": ["pd", "pps", "qi"], "year": 2023, "aliases": ["google pixel 8 pro"]},
    "pixel 8":           {"connector": "usb-c", "wired_w": 27, "wireless_w": 18,
                          "protocols": ["pd", "pps", "qi"], "year": 2023, "aliases": ["google pixel 8"]},
    "pixel 8a":          {"connector": "usb-c", "wired_w": 18, "wireless_w": 7.5,
                          "protocols": ["pd", "qi"], "year": 2024, "aliases": ["google pixel 8a"]},
    "pixel 7 pro":       {"connector": "usb-c", "wired_w": 23, "wireless_w": 23,
                          "protocols": ["pd", "pps", "qi"], "year": 2022, "aliases": ["google pixel 7 pro"]},
    "pixel 7":           {"connector": "usb-c", "wired_w": 20, "wireless_w": 20,
                          "protocols": ["pd", "pps", "qi"], "year": 2022, "aliases": ["google pixel 7"]},
    "pixel 7a":          {"connector": "usb-c", "wired_w": 18, "wireless_w": 5,
                          "protocols": ["pd", "qi"], "year": 2023, "aliases": ["google pixel 7a"]},
    "pixel 6 pro":       {"connector": "usb-c", "wired_w": 23, "wireless_w": 23,
                          "protocols": ["pd", "pps", "qi"], "year": 2021, "aliases": ["google pixel 6 pro"]},
    "pixel 6":           {"connector": "usb-c", "wired_w": 21, "wireless_w": 21,
                          "protocols": ["pd", "pps", "qi"], "year": 2021, "aliases": ["google pixel 6"]},
    "pixel 6a":          {"connector": "usb-c", "wired_w": 18, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2022, "aliases": ["google pixel 6a"]},
    "pixel fold":        {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2023, "aliases": ["google pixel fold"]},
    # ══════════════════ Nothing / CMF ══════════════════
    "nothing phone 3":   {"connector": "usb-c", "wired_w": 65, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025,
                          "aliases": ["nothing phone 3 pro", "phone 3"]},
    "nothing phone 2a":  {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2024,
                          "aliases": ["phone 2a", "nothing phone 2a plus"]},
    "nothing phone 2":   {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qc", "qi"], "year": 2023, "aliases": ["phone 2"]},
    "nothing phone 1":   {"connector": "usb-c", "wired_w": 33, "wireless_w": 15,
                          "protocols": ["pd", "qc", "qi"], "year": 2022, "aliases": ["phone 1"]},
    "cmf phone 2 pro":   {"connector": "usb-c", "wired_w": 33, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2025, "aliases": ["cmf phone 2"]},
    "cmf phone 1":       {"connector": "usb-c", "wired_w": 33, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024, "aliases": ["cmf 1"]},
    # ══════════════════ Sony / Asus / Motorola ══════════════════
    "xperia 1 vii":      {"connector": "usb-c", "wired_w": 30, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2025,
                          "aliases": ["sony xperia 1 vii", "xperia 1 mark 7"]},
    "xperia 1 vi":       {"connector": "usb-c", "wired_w": 30, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2024,
                          "aliases": ["sony xperia 1 vi", "xperia 1 mark 6"]},
    "xperia 1 v":        {"connector": "usb-c", "wired_w": 30, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qi"], "year": 2023,
                          "aliases": ["sony xperia 1 v", "xperia 1 mark 5"]},
    "xperia 5 v":        {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2023, "aliases": ["sony xperia 5 v"]},
    "xperia 10 vi":      {"connector": "usb-c", "wired_w": 18, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024, "aliases": ["sony xperia 10 vi"]},
    "rog phone 9":       {"connector": "usb-c", "wired_w": 65, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qc"], "year": 2024,
                          "aliases": ["asus rog phone 9", "rog 9"]},
    "rog phone 8":       {"connector": "usb-c", "wired_w": 65, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qc"], "year": 2024,
                          "aliases": ["asus rog phone 8", "rog 8"]},
    "rog phone 7":       {"connector": "usb-c", "wired_w": 65, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2023, "aliases": ["asus rog phone 7", "rog 7"]},
    "rog phone 6":       {"connector": "usb-c", "wired_w": 65, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2022, "aliases": ["asus rog phone 6", "rog 6"]},
    "zenfone 11 ultra":  {"connector": "usb-c", "wired_w": 65, "wireless_w": 15,
                          "protocols": ["pd", "pps", "qc"], "year": 2024,
                          "aliases": ["asus zenfone 11 ultra"]},
    "zenfone 10":        {"connector": "usb-c", "wired_w": 30, "wireless_w": 15,
                          "protocols": ["pd", "qc"], "year": 2023, "aliases": ["asus zenfone 10"]},
    "zenfone 9":         {"connector": "usb-c", "wired_w": 30, "wireless_w": 0,
                          "protocols": ["pd", "qc"], "year": 2022, "aliases": ["asus zenfone 9"]},
    "motorola edge 50 ultra": {"connector": "usb-c", "wired_w": 125, "wireless_w": 50,
                          "protocols": ["pd", "pps"], "year": 2024,
                          "aliases": ["edge 50 ultra", "moto edge 50 ultra"]},
    "motorola edge 50 pro": {"connector": "usb-c", "wired_w": 125, "wireless_w": 0,
                          "protocols": ["pd", "pps"], "year": 2024,
                          "aliases": ["edge 50 pro", "moto edge 50"]},
    "motorola edge 40 pro": {"connector": "usb-c", "wired_w": 125, "wireless_w": 15,
                          "protocols": ["pd", "pps"], "year": 2023,
                          "aliases": ["edge 40 pro", "moto edge 40"]},
    "motorola edge 40":  {"connector": "usb-c", "wired_w": 68, "wireless_w": 15,
                          "protocols": ["pd"], "year": 2023, "aliases": ["edge 40"]},
    "motorola razr 50 ultra": {"connector": "usb-c", "wired_w": 45, "wireless_w": 15,
                          "protocols": ["pd"], "year": 2024,
                          "aliases": ["razr 50 ultra", "razr 50", "moto razr"]},
    # ══════════════════ Infinix / Tecno / Itel (ตลาดไทย) ══════════════════
    "infinix note 40 pro plus": {"connector": "usb-c", "wired_w": 100, "wireless_w": 20,
                          "protocols": ["pd"], "year": 2024,
                          "aliases": ["infinix note 40 pro+", "note 40 pro"]},
    "infinix note 40":   {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024, "aliases": ["note 40"]},
    "infinix gt 20 pro": {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024, "aliases": ["gt 20 pro"]},
    "tecno camon 40":    {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2025, "aliases": ["camon 40"]},
    "tecno camon 30":    {"connector": "usb-c", "wired_w": 70, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2024, "aliases": ["camon 30"]},
    "tecno phantom x2":  {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2022, "aliases": ["phantom x2"]},
    # ══════════════════ Game handhelds ══════════════════
    "steam deck":        {"connector": "usb-c", "wired_w": 45, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2022,
                          "aliases": ["steam deck oled", "steamdeck"]},
    "rog ally":          {"connector": "usb-c", "wired_w": 65, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2023,
                          "aliases": ["asus rog ally", "rog ally x"]},
    "legion go":         {"connector": "usb-c", "wired_w": 65, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2023, "aliases": ["lenovo legion go"]},
    "nintendo switch":   {"connector": "usb-c", "wired_w": 39, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2017, "aliases": ["switch oled", "switch"]},
    "nintendo switch 2": {"connector": "usb-c", "wired_w": 60, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2025, "aliases": ["switch 2"]},
    "ps portal":         {"connector": "usb-c", "wired_w": 15, "wireless_w": 0,
                          "protocols": ["pd"], "year": 2023, "aliases": ["playstation portal"]},
}
